### ISSUE TITLE
Switching from windows_eventlog to windows_eventlog2 causes "no implicit conversion of Array into String" errors

### ISSUE THREAD

**Issue by danfinn** [fluent/fluent-plugin-windows-eventlog#101]
td-agent-4.0.1-x64.msi
Windows Server 2019

We've had some issues recently with windows event logs being shipped with non utf-8 characters which then causes all sorts of issues with log delivery to elasticsearch.  In an attempt to fix this I thought I would move to windows_eventlog2 as it sounds like this handles making sure that everything is utf-8 encoded.

Here is my current config:
```
<source>
  @type windows_eventlog
  @id windows_eventlog
  tag logs
  channels application,system,security
  <storage>
    @type local
    persistent true
    path c:/opt/td-agent/winevt.pos
  </storage>
  encoding utf-8
</source>
```

Which works fine and has been working for us for quite time.  Simply changing those @type and @id lines to windows_eventlog2 and keeping the rest of the config in place, I'm getting the following errors:

```
2023-09-15 20:03:43 +0000 [info]: #0 starting fluentd worker pid=5656 ppid=11244 worker=0
2023-09-15 20:03:43 +0000 [error]: #0 unexpected error error_class=TypeError error="no implicit conversion of Array into String"
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/sax/parser.rb:108:in `memory'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/sax/parser.rb:108:in `parse_memory'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/sax/parser.rb:83:in `parse'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-windows-eventlog-0.7.0/lib/fluent/plugin/in_windows_eventlog2.rb:174:in `bookmark_validator'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-windows-eventlog-0.7.0/lib/fluent/plugin/in_windows_eventlog2.rb:148:in `subscribe_channel'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-windows-eventlog-0.7.0/lib/fluent/plugin/in_windows_eventlog2.rb:141:in `block in start'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-windows-eventlog-0.7.0/lib/fluent/plugin/in_windows_eventlog2.rb:140:in `each'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-windows-eventlog-0.7.0/lib/fluent/plugin/in_windows_eventlog2.rb:140:in `start'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:200:in `block in start'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:188:in `each'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:175:in `each'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:175:in `lifecycle'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/root_agent.rb:199:in `start'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/engine.rb:248:in `start'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/engine.rb:147:in `run'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:603:in `block in run_worker'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:840:in `main_process'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/supervisor.rb:594:in `run_worker'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/command/fluentd.rb:361:in `<top (required)>'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/bin/fluentd:8:in `<top (required)>'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/bin/fluentd:23:in `load'
  2023-09-15 20:03:43 +0000 [error]: #0 c:/opt/td-agent/bin/fluentd:23:in `<main>'
2023-09-15 20:03:43 +0000 [error]: #0 unexpected error error_class=TypeError error="no implicit conversion of Array into String"
  2023-09-15 20:03:43 +0000 [error]: #0 suppressed same stacktrace
```

What is needed to be able to use windows_eventlog2 or to somehow force utf-8 encoding?

**Comment by danfinn** [comment]
I tried upgrading to: 
td-agent-4.5.1-x64.msi
fluent-plugin-windows-eventlog -v 0.8.3

and the error is slightly different but similar:
```
2023-09-18 21:26:05 +0000 [error]: #0 unexpected error error_class=TypeError error="wrong argument type Array (expected String)"
```

**Comment by danfinn** [comment]
looks like this may have been a config issue on my end, when I adjust my config to this it seems to be working, or at least stops erroring:

```
<source>
  @type windows_eventlog2
  @id windows_eventlog2
  tag logs
  channels application,system,security
  <storage>
    @type local
    persistent true
    #path c:/opt/td-agent/winevt.pos
    path ./tmp/storage.json
  </storage>
</source>
```
