### ISSUE TITLE
Error using windows_eventlog2

### ISSUE THREAD

**Issue by DaveSlinn** [fluent/fluent-plugin-windows-eventlog#25]
I followed thread #22 and was able to get to a point where it is finding plugin called windows_eventlog2 but I am getting error ``wrong argument type Array (expected String)``.  My config (as shown) is pretty simple. Thoughts?

Here is the full output:
```
C:\Ruby25-x64\bin>fluentd -c C:\opt\td-agent\etc\td-agent\td-agent.conf
2019-08-22 18:12:17 -0600 [info]: parsing config file is succeeded path="C:\\opt\\td-agent\\etc\\td-agent\\td-agent.conf"
2019-08-22 18:12:17 -0600 [info]: using configuration file: <ROOT>
  <source>
    @type windows_eventlog2
    @id windows_eventlog2
    channels cor
    tag "winevt.raw"
    <storage>
      @type "local"
      persistent true
      path "C:\\opt\\td-agent\\winevt.pos"
    </storage>
  </source>
  <match winevt.**>
    @type stdout
  </match>
</ROOT>
2019-08-22 18:12:17 -0600 [info]: starting fluentd-1.7.0 pid=17596 ruby="2.5.5"
2019-08-22 18:12:17 -0600 [info]: spawn command to main:  cmdline=["C:/Ruby25-x64/bin/ruby.exe", "-Eascii-8bit:ascii-8bit", "C:/Ruby25-x64/bin/fluentd", "-c", "C:\\opt\\td-agent\\etc\\td-agent\\td-agent.conf", "--under-supervisor"]
2019-08-22 18:12:19 -0600 [info]: gem 'fluent-plugin-windows-eventlog' version '0.3.0'
2019-08-22 18:12:19 -0600 [info]: gem 'fluentd' version '1.7.0'
2019-08-22 18:12:19 -0600 [info]: adding match pattern="winevt.**" type="stdout"
2019-08-22 18:12:19 -0600 [info]: adding source type="windows_eventlog2"
2019-08-22 18:12:20 -0600 [info]: #0 starting fluentd worker pid=28924 ppid=17596 worker=0
2019-08-22 18:12:20 -0600 [error]: #0 unexpected error error_class=TypeError error="wrong argument type Array (expected String)"
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluent-plugin-windows-eventlog-0.3.0/lib/fluent/plugin/in_windows_eventlog2.rb:77:in `initialize'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluent-plugin-windows-eventlog-0.3.0/lib/fluent/plugin/in_windows_eventlog2.rb:77:in `new'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluent-plugin-windows-eventlog-0.3.0/lib/fluent/plugin/in_windows_eventlog2.rb:77:in `block in start'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluent-plugin-windows-eventlog-0.3.0/lib/fluent/plugin/in_windows_eventlog2.rb:74:in `each'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluent-plugin-windows-eventlog-0.3.0/lib/fluent/plugin/in_windows_eventlog2.rb:74:in `start'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:203:in `block in start'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:191:in `each'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:178:in `each'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:178:in `lifecycle'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/root_agent.rb:202:in `start'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/engine.rb:274:in `start'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/engine.rb:219:in `run'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/supervisor.rb:808:in `run_engine'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/supervisor.rb:551:in `block in run_worker'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/supervisor.rb:733:in `main_process'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/supervisor.rb:546:in `run_worker'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/lib/fluent/command/fluentd.rb:320:in `<top (required)>'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/fluentd-1.7.0-x64-mingw32/bin/fluentd:8:in `<top (required)>'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/bin/fluentd:23:in `load'
  2019-08-22 18:12:20 -0600 [error]: #0 C:/Ruby25-x64/bin/fluentd:23:in `<main>'
2019-08-22 18:12:20 -0600 [error]: #0 unexpected error error_class=TypeError error="wrong argument type Array (expected String)"
  2019-08-22 18:12:20 -0600 [error]: #0 suppressed same stacktrace
2019-08-22 18:12:20 -0600 [info]: Worker 0 finished unexpectedly with status 1
2019-08-22 18:12:20 -0600 [info]: Received graceful stop
Traceback (most recent call last):
        29: from C:/Ruby25-x64/bin/fluentd:23:in `<main>'
        28: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:304:in `activate_bin_path'
        27: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:304:in `synchronize'
        26: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:306:in `block in activate_bin_path'
        25: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:243:in `finish_resolve'
        24: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/request_set.rb:397:in `resolve_current'
        23: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/request_set.rb:385:in `resolve'
        22: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:188:in `resolve'
        21: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        20: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
        19: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
        18: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
        17: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
        16: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
        15: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
        14: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `sort_dependencies'
        13: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `with_index'
        12: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `sort_by'
        11: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `each'
        10: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:281:in `block in sort_dependencies'
         9: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver.rb:303:in `amount_constrained'
         8: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/resolver/current_set.rb:10:in `find_all'
         7: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/dependency.rb:279:in `matching_specs'
         6: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:869:in `stubs_for'
         5: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:782:in `installed_stubs'
         4: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:790:in `map_stubs'
         3: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:790:in `flat_map'
         2: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:790:in `each'
         1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:793:in `block in map_stubs'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb:769:in `gemspec_stubs_in': Interrupt
2019-08-22 18:12:21 -0600 [info]: Worker 0 finished with status 3
```

**Comment by DaveSlinn** [comment]
I'm closing this issue. I updated my config to use the example in the readme and it is working.

**Comment by sophieyfang** [comment]
I saw this error too. I wonder which part of the config causes this array but expected string error msg...
